"""
FAQ Reflection Agent
====================
A LangGraph-based reflection agent that:
  - Generates FAQ answers using Ollama (local LLM) (Node 1)
  - Validates answers using Groq / LLaMA (Node 2)
  - Retries up to 3 times per question
  - Saves structured output to outputs/output.json

Workflow:
  load_question → generate_answer → validate_answer
                        ↑                  |
                        └──── retry ───────┘ (max 3 times)
                                           |
                                      save_result → [next question or END]

Prerequisites for Ollama:
  1. Install Ollama: https://ollama.com/download
  2. Pull a model: ollama pull llama3.2
  3. Ollama runs locally at http://localhost:11434 (no API key needed)
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from langchain_ollama import ChatOllama
from langchain_groq import ChatGroq
from langgraph.graph import END, StateGraph
from pydantic import BaseModel, Field
from typing_extensions import TypedDict

# ── Environment ──────────────────────────────────────────────────────────────
load_dotenv()

GROQ_API_KEY   = os.getenv("GROQ_API_KEY")
OLLAMA_MODEL   = os.getenv("OLLAMA_MODEL", "llama3.2")       # default model
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")

if not GROQ_API_KEY:
    raise EnvironmentError(
        "Missing GROQ_API_KEY. Please set it in .env"
    )

# ── File paths ────────────────────────────────────────────────────────────────
BASE_DIR    = Path(__file__).parent
INPUT_FILE  = BASE_DIR / "inputs"  / "input.json"
OUTPUT_FILE = BASE_DIR / "outputs" / "output.json"
OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

MAX_RETRIES = 3  # Maximum regeneration attempts per question


# ═══════════════════════════════════════════════════════════════════════════════
# Pydantic Schemas (Structured Outputs)
# ═══════════════════════════════════════════════════════════════════════════════

class GeneratedAnswer(BaseModel):
    """Schema for the answer produced by the Ollama generator node."""
    answer: str = Field(description="A clear, accurate, concise answer to the FAQ question.")


class ValidationResult(BaseModel):
    """Schema for the validation result produced by the Groq validator node."""
    is_valid: bool  = Field(description="True if the answer is accurate, relevant, and complete.")
    remarks:  str   = Field(description="Brief explanation of why the answer is valid or invalid.")


class FAQResult(BaseModel):
    """Schema for one fully-processed FAQ entry saved to output.json."""
    faqQuestion:    int
    Question:       str
    iterationCount: int
    status:         str   # "answered" | "no_answer"
    Answer:         str
    checkedAnswer:  bool
    remarks:        str


# ═══════════════════════════════════════════════════════════════════════════════
# LangGraph State
# ═══════════════════════════════════════════════════════════════════════════════

class AgentState(TypedDict):
    """
    Shared mutable state passed between all LangGraph nodes.

    Fields
    ------
    questions       : Full list of FAQ dicts loaded from input.json
    current_index   : Index of the question being processed right now
    current_question: The question text for the current FAQ
    faq_number      : The faqQuestion integer id
    current_answer  : Latest answer generated by Gemini
    iteration_count : How many generation attempts have been made (max 3)
    is_valid        : Whether the last validation passed
    remarks         : Validator's explanation
    results         : Accumulated list of FAQResult dicts for output.json
    """
    questions:        list[dict]
    current_index:    int
    current_question: str
    faq_number:       int
    current_answer:   str
    iteration_count:  int
    is_valid:         bool
    remarks:          str
    results:          list[dict]


# ═══════════════════════════════════════════════════════════════════════════════
# LLM Clients
# ═══════════════════════════════════════════════════════════════════════════════

# Node 1 – Generator (Ollama — local, no API key needed)
ollama_llm = ChatOllama(
    model=OLLAMA_MODEL,
    base_url=OLLAMA_BASE_URL,
    temperature=0.3,
)
generator_llm = ollama_llm.with_structured_output(GeneratedAnswer)

# Node 2 – Validator (Groq / LLaMA)
groq_llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    groq_api_key=GROQ_API_KEY,
)
validator_llm = groq_llm.with_structured_output(ValidationResult)


# ═══════════════════════════════════════════════════════════════════════════════
# Node 1 – Generate Answer  (Ollama)
# ═══════════════════════════════════════════════════════════════════════════════

def generate_answer(state: AgentState) -> AgentState:
    """
    Generator node: calls local Ollama to produce a structured FAQ answer.
    Increments iteration_count on each call.
    """
    question  = state["current_question"]
    iteration = state["iteration_count"] + 1

    print(f"  [Ollama] Generating answer (attempt {iteration}) for: '{question}'")

    prompt = (
        f"You are an expert technical writer.\n"
        f"Provide a clear, accurate, and concise answer (2-4 sentences) to this FAQ question:\n\n"
        f"Question: {question}"
    )

    result: GeneratedAnswer = generator_llm.invoke(prompt)

    return {
        **state,
        "current_answer":  result.answer,
        "iteration_count": iteration,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# Node 2 – Validate Answer  (Groq / LLaMA)
# ═══════════════════════════════════════════════════════════════════════════════

def validate_answer(state: AgentState) -> AgentState:
    """
    Validator node: calls Groq / LLaMA to verify the generated answer.
    Sets is_valid and remarks in state.
    """
    question = state["current_question"]
    answer   = state["current_answer"]

    print(f"  [Groq]   Validating answer for: '{question}'")

    prompt = (
        f"You are a strict quality-assurance reviewer.\n"
        f"Evaluate whether the following answer correctly and completely addresses the FAQ question.\n\n"
        f"Question : {question}\n"
        f"Answer   : {answer}\n\n"
        f"Return is_valid=true only if the answer is accurate, relevant, and at least 1 sentence long. "
        f"Provide a brief remark explaining your decision."
    )

    result: ValidationResult = validator_llm.invoke(prompt)

    print(f"  [Groq]   Valid={result.is_valid} | Remarks: {result.remarks}")

    return {
        **state,
        "is_valid": result.is_valid,
        "remarks":  result.remarks,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# Node 3 – Save Result
# ═══════════════════════════════════════════════════════════════════════════════

def save_result(state: AgentState) -> AgentState:
    """
    Persists the processed FAQ entry (valid or exhausted) into state["results"]
    and advances the current_index to the next question.
    """
    if state["is_valid"]:
        status        = "answered"
        answer        = state["current_answer"]
        checked       = True
        remarks       = state["remarks"]
    else:
        # All 3 retries exhausted without a valid answer
        status        = "no_answer"
        answer        = "-"
        checked       = False
        remarks       = "No valid answer after maximum retries."

    entry = FAQResult(
        faqQuestion    = state["faq_number"],
        Question       = state["current_question"],
        iterationCount = state["iteration_count"],
        status         = status,
        Answer         = answer,
        checkedAnswer  = checked,
        remarks        = remarks,
    )

    print(f"  [Save]   FAQ {state['faq_number']} → status='{status}' after {state['iteration_count']} attempt(s).\n")

    updated_results = state["results"] + [entry.model_dump()]
    next_index      = state["current_index"] + 1

    # Pre-load the next question into state (if it exists)
    questions = state["questions"]
    if next_index < len(questions):
        next_q      = questions[next_index]
        next_text   = next_q["Question"]
        next_faq_no = next_q["faqQuestion"]
    else:
        next_text   = ""
        next_faq_no = -1

    return {
        **state,
        "results":          updated_results,
        "current_index":    next_index,
        "current_question": next_text,
        "faq_number":       next_faq_no,
        "current_answer":   "",
        "iteration_count":  0,
        "is_valid":         False,
        "remarks":          "",
    }


# ═══════════════════════════════════════════════════════════════════════════════
# Conditional Routing Functions
# ═══════════════════════════════════════════════════════════════════════════════

def route_after_validation(state: AgentState) -> str:
    """
    After validation, decide next node:
      - "save_result"      → answer is valid
      - "generate_answer"  → answer invalid AND retries remaining
      - "save_result"      → answer invalid AND max retries exhausted (will store '-')
    """
    if state["is_valid"]:
        return "save_result"

    if state["iteration_count"] < MAX_RETRIES:
        print(f"  [Router] Invalid. Retrying (attempt {state['iteration_count'] + 1}/{MAX_RETRIES})...")
        return "generate_answer"

    print(f"  [Router] Max retries ({MAX_RETRIES}) reached. Saving as no_answer.")
    return "save_result"


def route_after_save(state: AgentState) -> str:
    """
    After saving a result, decide whether to process the next question or end.
    """
    if state["current_index"] < len(state["questions"]):
        return "generate_answer"   # More questions remain
    return END                     # All questions processed


# ═══════════════════════════════════════════════════════════════════════════════
# Build LangGraph StateGraph
# ═══════════════════════════════════════════════════════════════════════════════

def build_graph() -> StateGraph:
    """Constructs and compiles the reflection-agent StateGraph."""

    graph = StateGraph(AgentState)

    # Register nodes
    graph.add_node("generate_answer", generate_answer)
    graph.add_node("validate_answer", validate_answer)
    graph.add_node("save_result",     save_result)

    # Entry point
    graph.set_entry_point("generate_answer")

    # Fixed edges
    graph.add_edge("generate_answer", "validate_answer")

    # Conditional edges
    graph.add_conditional_edges(
        "validate_answer",
        route_after_validation,
        {
            "generate_answer": "generate_answer",  # retry loop
            "save_result":     "save_result",       # valid or exhausted
        },
    )

    graph.add_conditional_edges(
        "save_result",
        route_after_save,
        {
            "generate_answer": "generate_answer",  # next question
            END:               END,                # all done
        },
    )

    return graph.compile()


# ═══════════════════════════════════════════════════════════════════════════════
# Output Writer
# ═══════════════════════════════════════════════════════════════════════════════

def write_output(results: list[dict]) -> None:
    """Writes the final structured output to outputs/output.json."""
    output = {
        "totalQuestions": len(results),
        "processedAt":    datetime.now(timezone.utc).isoformat(),
        "results":        results,
    }
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
    print(f"\n✅ Output saved to: {OUTPUT_FILE}")


# ═══════════════════════════════════════════════════════════════════════════════
# Entry Point
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    # ── Load questions ────────────────────────────────────────────────────────
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        questions: list[dict] = json.load(f)

    if not questions:
        raise ValueError("input.json is empty. Please add FAQ questions.")

    print(f"\n{'═'*60}")
    print(f"  FAQ Reflection Agent  |  {len(questions)} questions")
    print(f"{'═'*60}\n")

    # ── Build graph ───────────────────────────────────────────────────────────
    app = build_graph()

    # ── Initial state (first question pre-loaded) ─────────────────────────────
    first_q = questions[0]
    initial_state: AgentState = {
        "questions":        questions,
        "current_index":    0,
        "current_question": first_q["Question"],
        "faq_number":       first_q["faqQuestion"],
        "current_answer":   "",
        "iteration_count":  0,
        "is_valid":         False,
        "remarks":          "",
        "results":          [],
    }

    # ── Run the graph ─────────────────────────────────────────────────────────
    final_state = app.invoke(initial_state)

    # ── Persist output ────────────────────────────────────────────────────────
    write_output(final_state["results"])

    # ── Summary ───────────────────────────────────────────────────────────────
    answered  = sum(1 for r in final_state["results"] if r["status"] == "answered")
    no_answer = len(final_state["results"]) - answered

    print(f"\n{'─'*60}")
    print(f"  Summary: {answered} answered  |  {no_answer} no_answer")
    print(f"{'─'*60}\n")


if __name__ == "__main__":
    main()