"""
state.py
========
Defines all Pydantic schemas (structured outputs) and the
LangGraph AgentState TypedDict shared across every node.
"""

from pydantic import BaseModel, Field
from typing_extensions import TypedDict



# Pydantic Schemas (Structured Outputs)

class GeneratedAnswer(BaseModel):
    """Schema for the answer produced by the Ollama generator node."""
    answer: str = Field(description="A clear, accurate, concise answer to the FAQ question.")


class ValidationResult(BaseModel):
    """Schema for the validation result produced by the Groq validator node."""
    is_valid: bool = Field(description="True if the answer is accurate, relevant, and complete.")
    remarks:  str  = Field(description="Brief explanation of why the answer is valid or invalid.")


class FAQResult(BaseModel):
    """Schema for one fully-processed FAQ entry saved to output.json."""
    faqQuestion:    int
    Question:       str
    iterationCount: int
    status:         str   # "answered" | "no_answer"
    Answer:         str
    checkedAnswer:  bool
    remarks:        str


# ═══════════════════════════════════════════════════════════════════════════════
# LangGraph Agent State
# ═══════════════════════════════════════════════════════════════════════════════

class AgentState(TypedDict):
    """
    Shared mutable state passed between all LangGraph nodes.

    Fields
    ------
    questions        : Full list of FAQ dicts loaded from input.json
    current_index    : Index of the question being processed right now
    current_question : The question text for the current FAQ
    faq_number       : The faqQuestion integer id
    current_answer   : Latest answer generated by Ollama
    iteration_count  : How many generation attempts have been made (max 3)
    is_valid         : Whether the last validation passed
    remarks          : Validator's explanation
    results          : Accumulated list of FAQResult dicts for output.json
    """
    questions:        list[dict]
    current_index:    int
    current_question: str
    faq_number:       int
    current_answer:   str
    iteration_count:  int
    is_valid:         bool
    remarks:          str
    results:          list[dict]